'use client';

import { useState, useEffect } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { Sparkles, FileText, Download, Loader2, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';

export default function GeneratePage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const grantId = searchParams.get('grantId');

  const [loading, setLoading] = useState(false);
  const [grantInfo, setGrantInfo] = useState<any>(null);
  const [generatedContent, setGeneratedContent] = useState<any>(null);

  // Form fields
  const [organizationName, setOrganizationName] = useState('');
  const [organizationType, setOrganizationType] = useState('');
  const [projectTitle, setProjectTitle] = useState('');
  const [projectSummary, setProjectSummary] = useState('');
  const [requestedAmount, setRequestedAmount] = useState('');
  const [projectDuration, setProjectDuration] = useState('');
  const [contactName, setContactName] = useState('');
  const [contactEmail, setContactEmail] = useState('');

  useEffect(() => {
    if (grantId) {
      fetchGrantInfo();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [grantId]);

  const fetchGrantInfo = async () => {
    try {
      const response = await fetch(`/api/opportunity/${grantId}`);
      if (response.ok) {
        const data = await response.json();
        setGrantInfo(data);
      }
    } catch (error) {
      console.error('Failed to fetch grant info:', error);
    }
  };

  const handleGenerate = async () => {
    if (!organizationName || !projectTitle || !projectSummary) {
      toast.error('Please fill in all required fields');
      return;
    }

    setLoading(true);
    setGeneratedContent(null);

    try {
      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          grantId,
          grantTitle: grantInfo?.title,
          grantAgency: grantInfo?.agency,
          organizationName,
          organizationType,
          projectTitle,
          projectSummary,
          requestedAmount,
          projectDuration,
          contactName,
          contactEmail,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate application');
      }

      const data = await response.json();
      setGeneratedContent(data);
      toast.success('Application generated successfully!');
    } catch (error) {
      console.error('Generation error:', error);
      toast.error('Failed to generate application. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleExportText = () => {
    if (!generatedContent) return;

    const grantRef = generatedContent.grant || grantInfo;
    const metadata = generatedContent.metadata || {};
    
    const content = `
═══════════════════════════════════════════════════════════════════
                    FEDERAL GRANT APPLICATION
                          DRAFT DOCUMENT
═══════════════════════════════════════════════════════════════════

Generated by GrantScope
Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

───────────────────────────────────────────────────────────────────
GRANT OPPORTUNITY INFORMATION
───────────────────────────────────────────────────────────────────

${grantRef ? `Grant Title: ${grantRef.title || 'N/A'}
Agency: ${grantRef.agency || 'N/A'}
Opportunity Number: ${grantRef.id || grantRef.number || grantRef.grantsgov_id || 'N/A'}
${grantRef.cfda ? `CFDA Number: ${grantRef.cfda}` : ''}
${grantRef.closeDate ? `Application Deadline: ${new Date(grantRef.closeDate).toLocaleDateString()}` : ''}
` : 'No grant reference selected'}

───────────────────────────────────────────────────────────────────
APPLICANT INFORMATION
───────────────────────────────────────────────────────────────────

Organization Name: ${metadata.organizationName || organizationName}
${metadata.organizationType ? `Organization Type: ${metadata.organizationType}` : ''}
Project Title: ${metadata.projectTitle || projectTitle}
${metadata.requestedAmount ? `Requested Funding: ${metadata.requestedAmount}` : ''}
${metadata.projectDuration ? `Project Duration: ${metadata.projectDuration}` : ''}
${metadata.contactName ? `Contact Person: ${metadata.contactName}` : ''}
${metadata.contactEmail ? `Contact Email: ${metadata.contactEmail}` : ''}


═══════════════════════════════════════════════════════════════════
                        EXECUTIVE SUMMARY
═══════════════════════════════════════════════════════════════════

${generatedContent.content?.executiveSummary || generatedContent.executiveSummary || generatedContent.abstract || 'Not generated'}


═══════════════════════════════════════════════════════════════════
                      GOALS AND OBJECTIVES
═══════════════════════════════════════════════════════════════════

${generatedContent.content?.goalsAndObjectives || generatedContent.goalsAndObjectives || generatedContent.goals || 'Not generated'}


═══════════════════════════════════════════════════════════════════
                       PROJECT NARRATIVE
═══════════════════════════════════════════════════════════════════

${generatedContent.content?.projectNarrative || generatedContent.projectNarrative || generatedContent.narrative || 'Not generated'}


═══════════════════════════════════════════════════════════════════
                  BUDGET NARRATIVE AND JUSTIFICATION
═══════════════════════════════════════════════════════════════════

${generatedContent.content?.budgetNarrative || generatedContent.budgetNarrative || generatedContent.budget || generatedContent.budgetJustification || 'Not generated'}


═══════════════════════════════════════════════════════════════════
                          DISCLAIMER
═══════════════════════════════════════════════════════════════════

This is an AI-generated draft document. It is provided as a starting point
and must be thoroughly reviewed, edited, and customized before submission.

The applicant is responsible for:
- Verifying accuracy of all information
- Ensuring compliance with grant requirements
- Obtaining necessary approvals and signatures
- Meeting all submission deadlines and requirements
- Following federal grant application guidelines

This document does not constitute legal advice or guarantee of grant award.

═══════════════════════════════════════════════════════════════════
                        END OF DOCUMENT
═══════════════════════════════════════════════════════════════════
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const filename = `grant-application-${(metadata.projectTitle || projectTitle).replace(/\s+/g, '-').toLowerCase()}-${new Date().getTime()}.txt`;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);

    toast.success('Exported to text file');
  };

  return (
    <div className="container px-4 py-8 max-w-5xl">
      {/* Header */}
      <Button variant="ghost" onClick={() => router.back()} className="mb-8">
        <ArrowLeft className="mr-2 h-4 w-4" />
        Back
      </Button>

      <div className="mb-8">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center">
            <Sparkles className="h-6 w-6 text-primary" />
          </div>
          <div>
            <h1 className="text-4xl font-bold">AI Grant Generator</h1>
            <p className="text-muted-foreground">
              Generate a tailored grant application using AI
            </p>
          </div>
        </div>

        {grantInfo && (
          <Card className="bg-muted/50">
            <CardContent className="pt-6">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <p className="font-semibold mb-1">{grantInfo.title}</p>
                  <p className="text-sm text-muted-foreground">{grantInfo.agency}</p>
                </div>
                <Badge>{grantInfo.status}</Badge>
              </div>
            </CardContent>
          </Card>
        )}
      </div>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* Input Form */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Application Information</CardTitle>
              <CardDescription>
                Provide details about your organization and project
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">
                  Organization Name <span className="text-destructive">*</span>
                </label>
                <Input
                  placeholder="Your organization name"
                  value={organizationName}
                  onChange={(e) => setOrganizationName(e.target.value)}
                />
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium">Organization Type</label>
                <Input
                  placeholder="e.g., Non-profit, University, Local Government"
                  value={organizationType}
                  onChange={(e) => setOrganizationType(e.target.value)}
                />
              </div>

              <Separator />

              <div className="space-y-2">
                <label className="text-sm font-medium">
                  Project Title <span className="text-destructive">*</span>
                </label>
                <Input
                  placeholder="Brief, descriptive project title"
                  value={projectTitle}
                  onChange={(e) => setProjectTitle(e.target.value)}
                />
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium">
                  Project Summary <span className="text-destructive">*</span>
                </label>
                <textarea
                  className="w-full min-h-[120px] px-3 py-2 text-sm rounded-md border border-input bg-background"
                  placeholder="Describe your project goals, activities, and expected outcomes..."
                  value={projectSummary}
                  onChange={(e) => setProjectSummary(e.target.value)}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Requested Amount</label>
                  <Input
                    type="text"
                    placeholder="$100,000"
                    value={requestedAmount}
                    onChange={(e) => setRequestedAmount(e.target.value)}
                  />
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium">Project Duration</label>
                  <Input
                    placeholder="12 months"
                    value={projectDuration}
                    onChange={(e) => setProjectDuration(e.target.value)}
                  />
                </div>
              </div>

              <Separator />

              <div className="space-y-2">
                <label className="text-sm font-medium">Contact Name</label>
                <Input
                  placeholder="Primary contact person"
                  value={contactName}
                  onChange={(e) => setContactName(e.target.value)}
                />
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium">Contact Email</label>
                <Input
                  type="email"
                  placeholder="contact@organization.org"
                  value={contactEmail}
                  onChange={(e) => setContactEmail(e.target.value)}
                />
              </div>

              <Button
                onClick={handleGenerate}
                disabled={loading}
                className="w-full"
                size="lg"
              >
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-5 w-5" />
                    Generate Application
                  </>
                )}
              </Button>

              <p className="text-xs text-muted-foreground text-center">
                Generation typically takes 30-60 seconds
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Generated Content */}
        <div className="space-y-6">
          {!generatedContent && !loading && (
            <Card>
              <CardContent className="pt-12 pb-12 text-center">
                <FileText className="h-16 w-16 mx-auto mb-4 text-muted-foreground" />
                <h3 className="text-lg font-semibold mb-2">No Content Generated Yet</h3>
                <p className="text-muted-foreground">
                  Fill in the form and click "Generate Application" to create your draft
                </p>
              </CardContent>
            </Card>
          )}

          {loading && (
            <Card>
              <CardContent className="pt-12 pb-12 text-center">
                <Loader2 className="h-16 w-16 mx-auto mb-4 text-primary animate-spin" />
                <h3 className="text-lg font-semibold mb-2">Generating Your Application</h3>
                <p className="text-muted-foreground">
                  Our AI is crafting a tailored grant application for you...
                </p>
              </CardContent>
            </Card>
          )}

          {generatedContent && (
            <>
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle>Generated Application</CardTitle>
                    <Button variant="outline" size="sm" onClick={handleExportText}>
                      <Download className="mr-2 h-4 w-4" />
                      Export
                    </Button>
                  </div>
                  <CardDescription>
                    Review and customize this AI-generated draft
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6">
                  {(generatedContent.content?.executiveSummary || generatedContent.executiveSummary || generatedContent.abstract) && (
                    <div>
                      <h4 className="font-semibold mb-3 text-lg">Executive Summary</h4>
                      <div className="prose prose-sm max-w-none">
                        <p className="text-sm text-muted-foreground whitespace-pre-wrap leading-relaxed">
                          {generatedContent.content?.executiveSummary || generatedContent.executiveSummary || generatedContent.abstract}
                        </p>
                      </div>
                    </div>
                  )}

                  {(generatedContent.content?.goalsAndObjectives || generatedContent.goalsAndObjectives || generatedContent.goals) && (
                    <>
                      <Separator />
                      <div>
                        <h4 className="font-semibold mb-3 text-lg">Goals and Objectives</h4>
                        <div className="prose prose-sm max-w-none">
                          <p className="text-sm text-muted-foreground whitespace-pre-wrap leading-relaxed">
                            {generatedContent.content?.goalsAndObjectives || generatedContent.goalsAndObjectives || generatedContent.goals}
                          </p>
                        </div>
                      </div>
                    </>
                  )}

                  {(generatedContent.content?.projectNarrative || generatedContent.projectNarrative || generatedContent.narrative) && (
                    <>
                      <Separator />
                      <div>
                        <h4 className="font-semibold mb-3 text-lg">Project Narrative</h4>
                        <div className="prose prose-sm max-w-none">
                          <p className="text-sm text-muted-foreground whitespace-pre-wrap leading-relaxed">
                            {generatedContent.content?.projectNarrative || generatedContent.projectNarrative || generatedContent.narrative}
                          </p>
                        </div>
                      </div>
                    </>
                  )}

                  {(generatedContent.content?.budgetNarrative || generatedContent.budgetNarrative || generatedContent.budget || generatedContent.budgetJustification) && (
                    <>
                      <Separator />
                      <div>
                        <h4 className="font-semibold mb-3 text-lg">Budget Narrative and Justification</h4>
                        <div className="prose prose-sm max-w-none">
                          <p className="text-sm text-muted-foreground whitespace-pre-wrap leading-relaxed">
                            {generatedContent.content?.budgetNarrative || generatedContent.budgetNarrative || generatedContent.budget || generatedContent.budgetJustification}
                          </p>
                        </div>
                      </div>
                    </>
                  )}
                </CardContent>
              </Card>

              <Card className="bg-orange-50 dark:bg-orange-950/20 border-orange-200 dark:border-orange-900">
                <CardContent className="pt-6">
                  <p className="text-sm text-orange-900 dark:text-orange-200">
                    <strong>Important:</strong> This is an AI-generated draft. Please review, 
                    edit, and customize all content before submission. Ensure accuracy of all 
                    information and compliance with grant requirements.
                  </p>
                </CardContent>
              </Card>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

